### ISSUE TITLE
Command to start GUI not found and failure to start CLI

### ISSUE THREAD

**Issue by KaMyKaSii** [XiaomiFirmwareUpdater/xiaomi-flashable-firmware-creator-gui#2]
Linux Mint 20.1. "$HOME/.local/bin" is present on PATH
```
matheus:[/media/matheus/ventoy/Files/PocoM3/update07]:
pip3 install -U xiaomi_flashable_firmware_creator_gui
Requirement already up-to-date: xiaomi_flashable_firmware_creator_gui in /home/matheus/.local/lib/python3.8/site-packages (2.3.0)
Requirement already satisfied, skipping upgrade: PyQt5<6.0.0,>=5.13.0 in /home/matheus/.local/lib/python3.8/site-packages (from xiaomi_flashable_firmware_creator_gui) (5.15.2)
Requirement already satisfied, skipping upgrade: xiaomi_flashable_firmware_creator<3.0.0,>=2.1.0 in /home/matheus/.local/lib/python3.8/site-packages (from xiaomi_flashable_firmware_creator_gui) (2.1.0)
Requirement already satisfied, skipping upgrade: PyQt5-sip<13,>=12.8 in /home/matheus/.local/lib/python3.8/site-packages (from PyQt5<6.0.0,>=5.13.0->xiaomi_flashable_firmware_creator_gui) (12.8.1)
Requirement already satisfied, skipping upgrade: remotezip<0.10.0,>=0.9.2 in /home/matheus/.local/lib/python3.8/site-packages (from xiaomi_flashable_firmware_creator<3.0.0,>=2.1.0->xiaomi_flashable_firmware_creator_gui) (0.9.2)
Requirement already satisfied, skipping upgrade: protobuf<4.0.0,>=3.14.0 in /home/matheus/.local/lib/python3.8/site-packages (from xiaomi_flashable_firmware_creator<3.0.0,>=2.1.0->xiaomi_flashable_firmware_creator_gui) (3.15.1)
Requirement already satisfied, skipping upgrade: requests in /usr/lib/python3/dist-packages (from remotezip<0.10.0,>=0.9.2->xiaomi_flashable_firmware_creator<3.0.0,>=2.1.0->xiaomi_flashable_firmware_creator_gui) (2.22.0)
Requirement already satisfied, skipping upgrade: tabulate in /home/matheus/.local/lib/python3.8/site-packages (from remotezip<0.10.0,>=0.9.2->xiaomi_flashable_firmware_creator<3.0.0,>=2.1.0->xiaomi_flashable_firmware_creator_gui) (0.8.8)
Requirement already satisfied, skipping upgrade: six>=1.9 in /usr/lib/python3/dist-packages (from protobuf<4.0.0,>=3.14.0->xiaomi_flashable_firmware_creator<3.0.0,>=2.1.0->xiaomi_flashable_firmware_creator_gui) (1.14.0)
matheus:[/media/matheus/ventoy/Files/PocoM3/update07]:
xiaomi-flashable-firmware-creator-gui
xiaomi-flashable-firmware-creator-gui: command not found
matheus:[/media/matheus/ventoy/Files/PocoM3/update07]:
xiaomi_flashable_firmware_creator -F miui_CITRUSEEAGlobal_V12.0.7.0.QJFEUXM_b40fb4b79d_10.0.zip
Traceback (most recent call last):
  File "/home/matheus/.local/bin/xiaomi_flashable_firmware_creator", line 5, in <module>
    from xiaomi_flashable_firmware_creator_gui.main import main
  File "/home/matheus/.local/lib/python3.8/site-packages/xiaomi_flashable_firmware_creator_gui/main.py", line 28, in <module>
    logging.basicConfig(filename=f'{current_dir}/data/last_run.log', filemode='w',
  File "/usr/lib/python3.8/logging/__init__.py", line 1976, in basicConfig
    h = FileHandler(filename, mode)
  File "/usr/lib/python3.8/logging/__init__.py", line 1143, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.8/logging/__init__.py", line 1172, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/media/matheus/ventoy/Files/PocoM3/update07/xiaomi_flashable_firmware_creator_gui/data/last_run.log'
matheus:[/media/matheus/ventoy/Files/PocoM3/update07]:
```

If I manually create the folder and log file then the CLI command will open the GUI, but without automatically selecting the action and zip file provided on the command line
```
mkdir -p /media/matheus/ventoy/Files/PocoM3/update07/xiaomi_flashable_firmware_creator_gui/data && touch /media/matheus/ventoy/Files/PocoM3/update07/xiaomi_flashable_firmware_creator_gui/data/last_run.log
```

**Comment by yshalsager** [comment]
@KaMyKaSii Fixed in https://github.com/XiaomiFirmwareUpdater/xiaomi-flashable-firmware-creator-gui/commit/5e5ece65d1439bef5a18541d0f4a507f0a0d1ab1
Please update the tool to v2.3.2 and use the command `xiaomi_flashable_firmware_creator_g` to run it.
