### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CanerKaraca23** [XiaomiFirmwareUpdater/xiaomi-flashable-firmware-creator-gui#33]
I got this error when i want to use the tool

`Traceback (most recent call last):
  File "C:\Users\caner\AppData\Roaming\Python\Python312\site-packages\xiaomi_flashable_firmware_creator_gui\main.py", line 512, in create_zip
    _, invalid_files = firmware_creator.extract()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caner\AppData\Roaming\Python\Python312\site-packages\xiaomi_flashable_firmware_creator\firmware_creator.py", line 486, in extract
    self.extractor.extract(files_to_extract)
  File "C:\Users\caner\AppData\Roaming\Python\Python312\site-packages\xiaomi_flashable_firmware_creator\extractors\zip_extractor.py", line 91, in extract
    self.handler.extract(files_to_extract)
  File "C:\Users\caner\AppData\Roaming\Python\Python312\site-packages\xiaomi_flashable_firmware_creator\extractors\handlers\android_one_zip.py", line 58, in extract
    parse_payload(self.payload, partition, out_f)
  File "C:\Users\caner\AppData\Roaming\Python\Python312\site-packages\xiaomi_flashable_firmware_creator\extractors\ota_payload_extractor\extract_android_ota_payload.py", line 99, in parse_payload
    r = decompress_payload('xzcat', data, e.num_blocks * BLOCK_SIZE, operation.data_sha256_hash)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caner\AppData\Roaming\Python\Python312\site-packages\xiaomi_flashable_firmware_creator\extractors\ota_payload_extractor\extract_android_ota_payload.py", line 82, in decompress_payload
    p = subprocess.Popen([command, '-'], stdout=subprocess.PIPE, stdin=subprocess.PIPE)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the specified file`

**Comment by yshalsager** [comment]
@CanerKaraca23 What's the tool version?

**Comment by CanerKaraca23** [comment]
> @CanerKaraca23 What's the tool version?

Latest, 2.3.17.

**Comment by yshalsager** [comment]
@CanerKaraca23 can you please send the command you are tring to run?

**Comment by yshalsager** [comment]
Another thing, the tool isn't tested on Py3.12 yet. so can you try using 3.11 and see?

**Comment by CanerKaraca23** [comment]
> @CanerKaraca23 can you please send the command you are tring to run?

I'm not running any command, i just opened GUI, selected rom zip and clicked start and then cmd gives this error. Will try on 3.11.

**Comment by CanerKaraca23** [comment]
Got same error. @yshalsager 

`Traceback (most recent call last):
  File "C:\Users\caner\AppData\Local\Programs\Python\Python311\Lib\site-packages\xiaomi_flashable_firmware_creator_gui\main.py", line 512, in create_zip
    _, invalid_files = firmware_creator.extract()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caner\AppData\Local\Programs\Python\Python311\Lib\site-packages\xiaomi_flashable_firmware_creator\firmware_creator.py", line 486, in extract
    self.extractor.extract(files_to_extract)
  File "C:\Users\caner\AppData\Local\Programs\Python\Python311\Lib\site-packages\xiaomi_flashable_firmware_creator\extractors\zip_extractor.py", line 91, in extract
    self.handler.extract(files_to_extract)
  File "C:\Users\caner\AppData\Local\Programs\Python\Python311\Lib\site-packages\xiaomi_flashable_firmware_creator\extractors\handlers\android_one_zip.py", line 58, in extract
    parse_payload(self.payload, partition, out_f)
  File "C:\Users\caner\AppData\Local\Programs\Python\Python311\Lib\site-packages\xiaomi_flashable_firmware_creator\extractors\ota_payload_extractor\extract_android_ota_payload.py", line 99, in parse_payload
    r = decompress_payload('xzcat', data, e.num_blocks * BLOCK_SIZE, operation.data_sha256_hash)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caner\AppData\Local\Programs\Python\Python311\Lib\site-packages\xiaomi_flashable_firmware_creator\extractors\ota_payload_extractor\extract_android_ota_payload.py", line 82, in decompress_payload
    p = subprocess.Popen([command, '-'], stdout=subprocess.PIPE, stdin=subprocess.PIPE)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caner\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\caner\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the specified file`

**Comment by yshalsager** [comment]
@CanerKaraca23 are you selecting a zip from C:/ drive?

**Comment by CanerKaraca23** [comment]
> @CanerKaraca23 are you selecting a zip from C:/ drive like downloads or documents? Try moving to somewhere else.

I'm selecting from Downloads. Will try on different folders.

**Comment by CanerKaraca23** [comment]
> > @CanerKaraca23 are you selecting a zip from C:/ drive like downloads or documents? Try moving to somewhere else.
> 
> I'm selecting from Downloads. Will try on different folders.

Tried on multiple different folders, still same error.

**Comment by CanerKaraca23** [comment]
Even cli version gives same error @yshalsager 

`Unzipping MIUI ROM...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\caner\AppData\Local\Programs\Python\Python311\Lib\site-packages\xiaomi_flashable_firmware_creator\__main__.py", line 5, in <module>
    main()
  File "C:\Users\caner\AppData\Local\Programs\Python\Python311\Lib\site-packages\xiaomi_flashable_firmware_creator\xiaomi_flashable_firmware_creator.py", line 43, in main
    new_zip = firmware_creator.auto()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caner\AppData\Local\Programs\Python\Python311\Lib\site-packages\xiaomi_flashable_firmware_creator\firmware_creator.py", line 522, in auto
    _, invalid_files = self.extract()
                       ^^^^^^^^^^^^^^
  File "C:\Users\caner\AppData\Local\Programs\Python\Python311\Lib\site-packages\xiaomi_flashable_firmware_creator\firmware_creator.py", line 486, in extract
    self.extractor.extract(files_to_extract)
  File "C:\Users\caner\AppData\Local\Programs\Python\Python311\Lib\site-packages\xiaomi_flashable_firmware_creator\extractors\zip_extractor.py", line 91, in extract
    self.handler.extract(files_to_extract)
  File "C:\Users\caner\AppData\Local\Programs\Python\Python311\Lib\site-packages\xiaomi_flashable_firmware_creator\extractors\handlers\android_one_zip.py", line 58, in extract
    parse_payload(self.payload, partition, out_f)
  File "C:\Users\caner\AppData\Local\Programs\Python\Python311\Lib\site-packages\xiaomi_flashable_firmware_creator\extractors\ota_payload_extractor\extract_android_ota_payload.py", line 99, in parse_payload
    r = decompress_payload('xzcat', data, e.num_blocks * BLOCK_SIZE, operation.data_sha256_hash)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caner\AppData\Local\Programs\Python\Python311\Lib\site-packages\xiaomi_flashable_firmware_creator\extractors\ota_payload_extractor\extract_android_ota_payload.py", line 82, in decompress_payload
    p = subprocess.Popen([command, '-'], stdout=subprocess.PIPE, stdin=subprocess.PIPE)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caner\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\caner\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the specified file`

**Comment by yshalsager** [comment]
> > @CanerKaraca23 are you selecting a zip from C:/ drive like downloads or documents? Try moving to somewhere else.
> 
> I'm selecting from Downloads. Will try on different folders.

Move to another drive please, it will work.

**Comment by CanerKaraca23** [comment]
> > > @CanerKaraca23 are you selecting a zip from C:/ drive like downloads or documents? Try moving to somewhere else.
> > 
> > 
> > I'm selecting from Downloads. Will try on different folders.
> 
> Move to another drive please, it will work.

I don't have another drive, will split but can it work on USB drive?

**Comment by yshalsager** [comment]
> I don't have another drive, will split but can it work on USB drive?

Try this solution https://stackoverflow.com/a/61766417

**Comment by CanerKaraca23** [comment]
> > I don't have another drive, will split but can it work on USB drive?
> 
> Try this solution https://stackoverflow.com/a/61766417

Disabled all security, moved to another drive, runned as administrator but still same error.

**Comment by yshalsager** [comment]
> > > I don't have another drive, will split but can it work on USB drive?
> > 
> > Try this solution https://stackoverflow.com/a/61766417
> 
> Disabled all security, moved to another drive, runned as administrator but still same error.
> 
> @yshalsager 

I would suggest running the tool from Windows subsystem for Linux (WSL)
